### ISSUE TITLE
Moved sd from rpi3b to Zero - no movement

### ISSUE THREAD

**Issue by puccaso** [CamJam-EduKit/EduKit3#17]
hello guys - 
how would one check to see if the headers are working correctly?
i have a pi zero and i moved everything across,
the sd card boots fine
however the motors dont move

**Comment by vincecr0ft** [comment]
I had a few issues with the pi zero at first but these all turned out to be my own poor wiring. 

I can confirm that both the gpio and zero codes run fine on a raspberry pi zero w.

But I would echo tips for how to trouble shoot when the motors don’t work. I have kits1 and 2 so I could test the libraries and the gpio connections but as soon as the hat goes on I’m stumped.

**Comment by chadananda** [comment]
Same experience. Would love to know how to test the hat.

**Comment by GeekyTim** [comment]
This is an OS issue which has been reported to the OS devs.
